# Default values for kiosk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

kiosk:
  command: 
  - /kiosk
  args: []
  resources:
    requests:
      memory: 128Mi
      cpu: 50m

serviceAccount:
  name: serviceaccount
  create: true
  clusterRole: cluster-admin

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443
  targetPort: 9443
