apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.tenancy.kiosk.sh
spec:
  version: v1alpha1
  versionPriority: 1000
  group: tenancy.kiosk.sh
  groupPriorityMinimum: 10000
  service:
    name: kiosk-apiservice
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: kiosk-apiservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiosk.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: {{ template "kiosk.fullname" . }}
    release: {{ .Release.Name }}
