apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kiosk.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiosk.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "kiosk.fullname" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "kiosk.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ template "kiosk.serviceAccountName" . }}
      containers:
      - command:
        {{- range $f := .Values.kiosk.command }}
        - {{ $f | quote }}
        {{- end }}
        args:
        {{- range $f := .Values.kiosk.args }}
        - {{ $f | quote }}
        {{- end }}
        {{- if .Values.image }}
        image: "{{ .Values.image }}"
        {{- else }}
        image: "kiosksh/kiosk:{{ .Chart.Version }}"
        {{- end }}
        name: kiosk
        resources:
{{ toYaml .Values.kiosk.resources | indent 10 }}
