name: Publish Release

on:
  release:
    types: [created]
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "hack/test.sh"
      - ".github/workflows/release.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - "hack/test.sh"
      - ".github/workflows/release.yaml"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Test
        run: ./hack/test.sh
  release:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: jerray/publish-docker-action@v1.0.3
        with:
          auto_tag: true
          repository: kiosksh/kiosk
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: azure/setup-helm@v1
        with:
          version: "v3.0.3"
      - run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/v!!p')
          helm plugin install https://github.com/chartmuseum/helm-push
          helm repo add chartmuseum $CHART_MUSEUM_URL --username $CHART_MUSEUM_USER --password $CHART_MUSEUM_PASSWORD
          helm push --force --version="$RELEASE_VERSION" ./chart chartmuseum
        env:
          CHART_MUSEUM_URL: "https://charts.devspace.sh/"
          CHART_MUSEUM_USER: ${{ secrets.CHART_MUSEUM_USER }}
          CHART_MUSEUM_PASSWORD: ${{ secrets.CHART_MUSEUM_PASSWORD }}
